### ISSUE TITLE
[Function Request] Make slider return number only instead of array

### ISSUE THREAD

**Issue by arshx86** [BayBreezy/ui-thing#38]
The main issue of ShadCN is complexity, most of the components (`checkbox, slider, switch`) is not supporting `v-model` binding as default. Making us adding two seperate directivies to handle a very basic states.

UI Thing is extremely beatiful and for me its the best one.

My enhancement idea is support v-model as well as defaults value from it.
I dont think anyone would like their value as array in slider :) (or add two seperate directive for basic checkbox behaviour)
if you fix these you would have resolved all the issues of original shadcn and allow us to simplify our code, thanks! appreciate your work.

**Comment by BayBreezy** [comment]
I can try lol

**Comment by BayBreezy** [comment]
So.. after some checking around, I will say that this is not possible with the current implementation because UI Thing is using Radix Vue underneath it all.

One solution that I found is to use an external package and update the styles. That package is [VueForm Slider](https://github.com/vueform/slider).

After I add it to the docs, I will link it here

**Comment by BayBreezy** [comment]
Hey @arshx86 

Checkout this page https://ui-thing.behonbaker.com/forms/vee-vueformslider.

Let me know if you have any trouble with it
