### ISSUE TITLE
ERROR ExperimentalWarning: CommonJS module is loading ES Module

### ISSUE THREAD

**Issue by davidreyg** [BayBreezy/ui-thing#49]
Hi. :)
I'm having this issue in fresh nuxt app installation.

Using Node LTS version (22.12.0) produces this error/warning:

```
[4:24:26 PM]  ERROR  (node:94662) ExperimentalWarning: CommonJS module [...]/nuxt3-app/.nuxt/tailwind.config.cjs is loading ES Module [...]/nuxt3-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
```

**Comment by BayBreezy** [comment]
Hello @davidreyg ,

Thanks for reporting this.

Its more of an issue with your node version than anything else.

I saw it too when I tried node v22.

To get pass it, just change the require at the top of the file to import.

```js
import { fontFamily } from "tailwindcss/defaultTheme";
```

I don't want to change it in the CLI just yet because most ppl aren't using a higher version of node.
